spring:
  datasource:
    # MySQL
    #    url: jdbc:mysql://app-23d40f854d2f19bc88d7fa89fd2a3bbf-chart.50010-f7a49c.svc.cluster.local:3306/project_db?serverTimezone=Asia/Seoul
    #    username: root
    #    password: 1234
    #    driver-class-name: com.mysql.cj.jdbc.Driver

    # MariaDB
    url: jdbc:mariadb://localhost:13307/project_db?serverTimezone=Asia/Seoul
    username: root
    password: password1!
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true # SQL 개행
        highlight_sql: true
        use_sql_comments: true # 실행되는 쿼리문 HINT 표시
    #    database-platform: org.hibernate.dialect.MySQL8Dialect
    database-platform: org.hibernate.dialect.MariaDB103Dialect
    defer-datasource-initialization: true
  sql:
    init:
      platform: mysql
      mode: always

logging:
  level:
    root: debug
